"""added title and job position to the users table

Revision ID: 2bc3a9c80deb
Revises: a4963bfce4b4
Create Date: 2025-03-11 12:35:20.202579

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2bc3a9c80deb'
down_revision: Union[str, None] = 'a4963bfce4b4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('admins', 'reset_password',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('companies', 'transactional_currency',
               existing_type=sa.VARCHAR(length=3),
               nullable=True)
    op.add_column('users', sa.Column('title', sa.String(), nullable=True))
    op.add_column('users', sa.Column('job_position', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'job_position')
    op.drop_column('users', 'title')
    op.alter_column('companies', 'transactional_currency',
               existing_type=sa.VARCHAR(length=3),
               nullable=True)
    op.alter_column('admins', 'reset_password',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    # ### end Alembic commands ###
