"""added creator to user talbe

Revision ID: 3eb35884d5d1
Revises: e5c57871505e
Create Date: 2025-03-05 14:50:39.812779

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3eb35884d5d1'
down_revision: Union[str, None] = 'e5c57871505e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('created_by_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'users', 'users', ['created_by_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_column('users', 'created_by_id')
    # ### end Alembic commands ###
