"""removed verifier from users to admins

Revision ID: 3f9a004cbde7
Revises: ca0593c8bea5
Create Date: 2025-03-12 10:46:24.373534

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3f9a004cbde7'
down_revision: Union[str, None] = 'ca0593c8bea5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('admins', 'reset_password',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('companies', 'transactional_currency',
               existing_type=sa.VARCHAR(length=3),
               nullable=False)
    op.drop_constraint('documents_verifier_id_fkey', 'documents', type_='foreignkey')
    op.create_foreign_key(None, 'documents', 'admins', ['verifier_id'], ['id'], ondelete='SET NULL')
    op.alter_column('users', 'is_transact_portal_user',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'is_transact_portal_user',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.drop_constraint(None, 'documents', type_='foreignkey')
    op.create_foreign_key('documents_verifier_id_fkey', 'documents', 'users', ['verifier_id'], ['id'], ondelete='SET NULL')
    op.alter_column('companies', 'transactional_currency',
               existing_type=sa.VARCHAR(length=3),
               nullable=True)
    op.alter_column('admins', 'reset_password',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    # ### end Alembic commands ###
