"""removed has_portal_access field from  users table

Revision ID: 574f82ec5b09
Revises: 2bc3a9c80deb
Create Date: 2025-03-11 12:59:54.616758

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '574f82ec5b09'
down_revision: Union[str, None] = '2bc3a9c80deb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('admins', 'reset_password',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('companies', 'transactional_currency',
               existing_type=sa.VARCHAR(length=3),
               nullable=True)
    op.drop_column('users', 'has_portal_access')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('has_portal_access', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.alter_column('companies', 'transactional_currency',
               existing_type=sa.VARCHAR(length=3),
               nullable=True)
    op.alter_column('admins', 'reset_password',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    # ### end Alembic commands ###
