"""added creator to the payments table

Revision ID: 5e4aa4ed0d04
Revises: 3eb35884d5d1
Create Date: 2025-03-05 23:01:57.862516

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5e4aa4ed0d04'
down_revision: Union[str, None] = '3eb35884d5d1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payments', sa.Column('created_by_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'payments', 'users', ['created_by_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'payments', type_='foreignkey')
    op.drop_column('payments', 'created_by_id')
    # ### end Alembic commands ###
