"""added creator to Documents

Revision ID: 7325664f4a84
Revises: 8e3a8f31c700
Create Date: 2025-03-07 12:25:54.718436

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7325664f4a84'
down_revision: Union[str, None] = '8e3a8f31c700'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('created_by_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'documents', 'admins', ['created_by_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'documents', type_='foreignkey')
    op.drop_column('documents', 'created_by_id')
    # ### end Alembic commands ###
