"""added creator to kyc accounts

Revision ID: 83555b95de21
Revises: 7325664f4a84
Create Date: 2025-03-07 12:26:40.989612

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '83555b95de21'
down_revision: Union[str, None] = '7325664f4a84'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('kyc_accounts', sa.Column('created_by_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'kyc_accounts', 'admins', ['created_by_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'kyc_accounts', type_='foreignkey')
    op.drop_column('kyc_accounts', 'created_by_id')
    # ### end Alembic commands ###
