"""made portal access not null

Revision ID: 85f0706ce83b
Revises: b5a83f0d3b20
Create Date: 2025-03-07 12:32:41.043239

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '85f0706ce83b'
down_revision: Union[str, None] = 'b5a83f0d3b20'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'has_portal_access',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'has_portal_access',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    # ### end Alembic commands ###
