"""added creator to Companies

Revision ID: 8e3a8f31c700
Revises: ec2d0313e05e
Create Date: 2025-03-07 12:23:41.014325

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8e3a8f31c700'
down_revision: Union[str, None] = 'ec2d0313e05e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('companies', sa.Column('created_by_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'companies', 'admins', ['created_by_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'companies', type_='foreignkey')
    op.drop_column('companies', 'created_by_id')
    # ### end Alembic commands ###
