"""added nia verification status to users table

Revision ID: 98b86415eafd
Revises: 3f9a004cbde7
Create Date: 2025-03-12 12:26:12.520674

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '98b86415eafd'
down_revision: Union[str, None] = '3f9a004cbde7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('nia_verification_status', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'nia_verification_status')
    # ### end Alembic commands ###
