"""add transactions and user relationship

Revision ID: a045c18b1d87
Revises: 8f7734f81d9a
Create Date: 2025-03-05 12:45:24.265448

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a045c18b1d87'
down_revision: Union[str, None] = '8f7734f81d9a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('transactions',
    sa.Column('source_account_name', sa.String(length=50), nullable=False),
    sa.Column('source_account_number', sa.String(length=50), nullable=False),
    sa.Column('source_bank_sort_code', sa.String(length=50), nullable=False),
    sa.Column('source_bank_name', sa.String(length=50), nullable=False),
    sa.Column('recipient_bank_sort_code', sa.String(length=50), nullable=False),
    sa.Column('recipient_bank_name', sa.String(length=50), nullable=False),
    sa.Column('recipient_account_number', sa.String(length=50), nullable=False),
    sa.Column('recipient_account_name', sa.String(length=50), nullable=False),
    sa.Column('amount', sa.Float(), server_default='0.00', nullable=False),
    sa.Column('reference', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('reference_code', sa.String(length=50), nullable=False),
    sa.Column('transaction_reference', sa.String(length=50), nullable=False),
    sa.Column('authorizer', sa.String(length=50), nullable=True),
    sa.Column('confirmed_at', sa.DateTime(), nullable=False),
    sa.Column('balance_before', sa.Float(), server_default='0.00', nullable=True),
    sa.Column('balance_after', sa.Float(), server_default='0.00', nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('payment_id', sa.Integer(), nullable=True),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['payment_id'], ['payments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_transactions_id'), 'transactions', ['id'], unique=False)
    op.create_index(op.f('ix_transactions_recipient_account_name'), 'transactions', ['recipient_account_name'], unique=False)
    op.create_index(op.f('ix_transactions_recipient_account_number'), 'transactions', ['recipient_account_number'], unique=False)
    op.create_index(op.f('ix_transactions_recipient_bank_name'), 'transactions', ['recipient_bank_name'], unique=False)
    op.create_index(op.f('ix_transactions_recipient_bank_sort_code'), 'transactions', ['recipient_bank_sort_code'], unique=False)
    op.create_index(op.f('ix_transactions_reference'), 'transactions', ['reference'], unique=False)
    op.create_index(op.f('ix_transactions_reference_code'), 'transactions', ['reference_code'], unique=False)
    op.create_index(op.f('ix_transactions_source_account_name'), 'transactions', ['source_account_name'], unique=False)
    op.create_index(op.f('ix_transactions_source_account_number'), 'transactions', ['source_account_number'], unique=False)
    op.create_index(op.f('ix_transactions_source_bank_name'), 'transactions', ['source_bank_name'], unique=False)
    op.create_index(op.f('ix_transactions_source_bank_sort_code'), 'transactions', ['source_bank_sort_code'], unique=False)
    op.create_index(op.f('ix_transactions_transaction_reference'), 'transactions', ['transaction_reference'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_transactions_transaction_reference'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_source_bank_sort_code'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_source_bank_name'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_source_account_number'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_source_account_name'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_reference_code'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_reference'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_recipient_bank_sort_code'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_recipient_bank_name'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_recipient_account_number'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_recipient_account_name'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_id'), table_name='transactions')
    op.drop_table('transactions')
    # ### end Alembic commands ###
