"""added transactional currency and website field to company table

Revision ID: a4963bfce4b4
Revises: f0f666b92b66
Create Date: 2025-03-11 12:16:22.945087

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a4963bfce4b4'
down_revision: Union[str, None] = 'f0f666b92b66'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('admins', 'reset_password',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.add_column('companies', sa.Column('transactional_currency', sa.String(length=3), nullable=True))
    op.add_column('companies', sa.Column('website', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('companies', 'website')
    op.drop_column('companies', 'transactional_currency')
    op.alter_column('admins', 'reset_password',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    # ### end Alembic commands ###
