"""added creator to payments

Revision ID: b5a83f0d3b20
Revises: 83555b95de21
Create Date: 2025-03-07 12:27:24.289802

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b5a83f0d3b20'
down_revision: Union[str, None] = '83555b95de21'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payments', sa.Column('created_by_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'payments', 'admins', ['created_by_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'payments', type_='foreignkey')
    op.drop_column('payments', 'created_by_id')
    # ### end Alembic commands ###
