"""added user company relation

Revision ID: e5c57871505e
Revises: a045c18b1d87
Create Date: 2025-03-05 14:39:51.687761

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e5c57871505e'
down_revision: Union[str, None] = 'a045c18b1d87'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payments', sa.Column('user_id', sa.Integer(), nullable=True))
    op.alter_column('payments', 'company_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.create_foreign_key(None, 'payments', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'payments', type_='foreignkey')
    op.alter_column('payments', 'company_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('payments', 'user_id')
    # ### end Alembic commands ###
