"""added creator to users

Revision ID: ec2d0313e05e
Revises: c050c3af9886
Create Date: 2025-03-07 12:17:46.934446

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ec2d0313e05e'
down_revision: Union[str, None] = 'c050c3af9886'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('created_by_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'users', 'admins', ['created_by_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_column('users', 'created_by_id')
    # ### end Alembic commands ###
