"""added reset password field for admins

Revision ID: f0f666b92b66
Revises: 870894ee9fd1
Create Date: 2025-03-10 14:42:56.908199

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f0f666b92b66'
down_revision: Union[str, None] = '870894ee9fd1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('admins', sa.Column('reset_password', sa.Boolean(), nullable=True))
    op.alter_column('admins', 'password',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('admins', 'password',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('admins', 'reset_password')
    # ### end Alembic commands ###
